version: '3.8'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    hostname: influxdb
    container_name: influxdb
    ports:
      - "9999:9999"
  
  influxdb-sidecar-setup:
    image: emanuelefalzone/influxdb-sidecar-setup:1.0.0
    hostname: influxdb-sidecar-setup
    container_name: influxdb-sidecar-setup
    environment:
      INFLUX_HOSTNAME: influxdb 
      INFLUX_USERNAME: admin 
      INFLUX_PASSWORD: password 
      INFLUX_TOKEN: "d2VsY29tZQ==" 
      INFLUX_ORGANIZATION: polimi 
      INFLUX_BUCKET: bucket
      INFLUX_RETENTION_PERIOD: 0

  telegraf:
    image: your_telegraf_extension:your_awesome_tag
    hostname: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf:/etc/telegraf

networks:
  default:
    external:
        name: bank-network